/* Generated By:JJTree: Do not edit this line. ASTconditional_force_assignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTconditional_force_assignment extends SimpleNode {
  public ASTconditional_force_assignment(int id) {
    super(id);
  }

  public ASTconditional_force_assignment(VhdlParserCore p, int id) {
    super(id);
  }

}
/* JavaCC - OriginalChecksum=3d5d725fcec55f6146d327fc8c3aff82 (do not edit this line) */
