/* Generated By:JJTree: Do not edit this line. ASTsimple_release_assignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTsimple_release_assignment extends SimpleNode {
  public ASTsimple_release_assignment(int id) {
    super(id);
  }

  public ASTsimple_release_assignment(VhdlParserCore p, int id) {
    super(id);
  }

}
/* JavaCC - OriginalChecksum=9f629da8faa14e1bb7f119ad9aecf212 (do not edit this line) */
