/* Generated By:JJTree: Do not edit this line. ASTselected_force_assignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTselected_force_assignment extends SimpleNode {
  public ASTselected_force_assignment(int id) {
    super(id);
  }

  public ASTselected_force_assignment(VhdlParserCore p, int id) {
    super(id);
  }

}
/* JavaCC - OriginalChecksum=d20787146c40540c73d823f2a630ffa3 (do not edit this line) */
