/* Generated By:JJTree: Do not edit this line. ASTsimple_force_assignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package net.sourceforge.veditor.parser.vhdl;

public
class ASTsimple_force_assignment extends SimpleNode {
  public ASTsimple_force_assignment(int id) {
    super(id);
  }

  public ASTsimple_force_assignment(VhdlParserCore p, int id) {
    super(id);
  }

}
/* JavaCC - OriginalChecksum=442805e0862d6ad507c67c40940cc2e2 (do not edit this line) */
